---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baselime-collector
rules:
- apiGroups:
  - ""
  resources:
    - namespaces
    - deployments
    - pods
    - events
  verbs:
    - get
    - list
    - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: baselime-collector
roleRef:
  kind: ClusterRole
  name: baselime-collector
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: baselime-collector
  namespace: default