apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
data:
  fluent-bit.conf: |
    [SERVICE]
      Flush        30

    [INPUT]
      Name         tail
      Path         /var/log/containers/*.log
      Exclude_Path /var/log/containers/*baselime*
      Tag          kube.*
      DB           /var/log/flb_kube.db
      Mem_Buf_Limit 5MB
      Skip_Long_Lines On
      Refresh_Interval 10
      Rotate_Wait   30

    [FILTER]
      Name         kubernetes
      Match        kube.*
      Kube_URL     https://kubernetes.default.svc:443
      Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
      Kube_Tag_Prefix kube.var.log.containers.
      Merge_Log        On
      Merge_Log_Key    log_processed

    [OUTPUT]
      Name         http
      Host         events.baselime.io
      Port         443
      URI          /v1/logs
      Format       json
      TLS          On
      Header       x-api-key {{ .Values.apiKey }}
      Header       baselime-data-source fluentbit/k8s
      Match        kube.*